// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2d_8G-bO4Ye8Gv2BZE8dpf5juR9cU9OQ',
    appId: '1:117504445302:web:d753ffdac61b0f56690857',
    messagingSenderId: '117504445302',
    projectId: 'netflix-clone-2a915',
    authDomain: 'netflix-clone-2a915.firebaseapp.com',
    storageBucket: 'netflix-clone-2a915.appspot.com',
    measurementId: 'G-80G2F1QXRS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXh2kY7SJy9AzAKjzn5x2IelPbob4Ts98',
    appId: '1:117504445302:android:00c9409359b6bc15690857',
    messagingSenderId: '117504445302',
    projectId: 'netflix-clone-2a915',
    storageBucket: 'netflix-clone-2a915.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4kVGbjI0ZRJCaej9w-458ah1LCB8eRys',
    appId: '1:117504445302:ios:fca88ebfcfe1fcca690857',
    messagingSenderId: '117504445302',
    projectId: 'netflix-clone-2a915',
    storageBucket: 'netflix-clone-2a915.appspot.com',
    iosBundleId: 'com.example.mobDevFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4kVGbjI0ZRJCaej9w-458ah1LCB8eRys',
    appId: '1:117504445302:ios:679f5c7adf003a1f690857',
    messagingSenderId: '117504445302',
    projectId: 'netflix-clone-2a915',
    storageBucket: 'netflix-clone-2a915.appspot.com',
    iosBundleId: 'com.example.mobDevFinal.RunnerTests',
  );
}
